// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, Bucket, KvCache, Logger, MRNObject, ServiceStub, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API: ServiceStub<import('../api/index.js').default>;
  APP_DATA: SqlDatabase;
  logger: Logger;
  mem: KvCache;
  tracer: Tracer;
  USER_PHOTOS: Bucket;
}
